name = "Jatsmmp"
author = "Gera + EthicalObligation"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7e19a6d45c89852dc5a6e4afedb8e1ba3fd6e424be8fa13c41210c725f0f444"

[versions]
forge = "14.23.0.2486"
minecraft = "1.12.2"
