name = "Jatsmmp"
author = "Gera + EthicalObligation"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0ee2dfa02b2a2b3ebe02d42473cc6ec317cd27d6bfd252bb2870f16821f27aa"

[versions]
forge = "14.23.0.2486"
minecraft = "1.12.2"
