name = "Jatsmmp"
author = "Gera + EthicalObligation"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e8f9fb0f681b07b14e67f8b1a44047c1316e67c21f2263012a1ce0a4b081f0f"

[versions]
forge = "14.23.0.2486"
minecraft = "1.12.2"
